#! /bin/bash

bold=$(tput bold)
normal=$(tput sgr0)

file="src/test_adjacency_matrix.py"
echo "• ${bold}RUNNING${normal} $file"
python3.7 $file
echo

file="src/test_graph.py"
echo "• ${bold}RUNNING${normal} $file"
python3.7 $file
echo

file="src/test_cycles.py"
echo "• ${bold}RUNNING${normal} $file"
python3.7 $file
